{% set version = "3.0.14" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tweedie
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tweedie_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tweedie/tweedie_{{ version }}.tar.gz
  sha256: ea28ec5672a65df1f04775ffa231859671fbb5090dcd8db1668a3f41c838fbde

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}        # [unix]
    - {{ stdlib("c") }}          # [unix]
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-lifecycle >=1.0.0
    - r-statmod >=1.4.0
  run:
    - r-base
    - r-lifecycle >=1.0.0
    - r-statmod >=1.4.0

test:
  commands:
    - $R -e "library('tweedie')"           # [unix]
    - "\"%R%\" -e \"library('tweedie')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=tweedie
  license: GPL-2.0-or-later
  summary: Maximum likelihood computations for Tweedie families, including the series expansion (Dunn and Smyth, 2005; <doi10.1007/s11222-005-4070-y>) and the Fourier inversion  (Dunn and Smyth, 2008; <doi:10.1007/s11222-007-9039-6>), and related methods.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - npavlovikj
