appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: ikeSarq+z8fKbUmhRp3Fid/Yj58ya6+5Weja9UOmgk/i4UwlV7MvJkF9vE7W85NakGEGFFPcAyEac5p+qSF8meBSifrq2Qxuaelv936slbIdyqKn97a3EGwKBCchuvSfHB6Fc+EqVV+z+9jYnvhpXkCdYUVbxCd08VjjZXlHdJ0JGpiApugEYIUEYEmmtkF/e27402qhK9yvBYbxy2uEHKZcUTTNxV4O9CvnmEZEaRwTImvb2AKcjps5WcZdIi17jNwMoCJR1USoNnHU7qcIMy3FMtUfiDuNDY+7Yb/JDxYEvcVUMBYFZvWlpwI6rt2chqAnZKQlzCWvS1QG3ZjHIe96VyRMvoJdNJKvVvx9kpGYLX7evK8oL5py1zxdXdJl4Cjo+FDzTEL3JDCbozx72iUace1hJrCCEF6yW4rHS7W/LqDzfXlMi+IEiZYCRNikZBj7lU7KFICZxmPpiUsHZypsy77hTW0Anz4FDgrEEDBpQWtfXWEnoOJGfCyVgNMDhQZE5B/L45rCtaupCayUIH2r/0mrU2CvpPty0Y2tRDbkRRgCRorjK2XMc6xIcf80a45Ia2Phln5GRsCUXOAsj289S7byNadgp3Pzp4+hlLGBihGL6tOrbidsrshW72dt9A0OLGui2DXtjTrQ/6Pg02Al07YsDQCEstMks83YwTk=
